# Generated by Django 2.1.3 on 2020-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='default_template_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ruta de la plantilla per defecte'),
        ),
    ]
