# Generated by Django 2.2.15 on 2020-09-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager', '0002_auto_20200401_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'mail template', 'verbose_name_plural': 'mail templates'},
        ),
    ]
