# Generated by Django 2.2.14 on 2020-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager', '0003_auto_20200914_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='default_template_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='default template path'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='text_identifier',
            field=models.CharField(max_length=100, unique=True, verbose_name='identifier'),
        ),
    ]
