# Generated by Django 2.2.7 on 2020-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_manager', '0004_auto_20200928_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(verbose_name='cos'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creació'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='default_template_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ruta de la plantilla per defecte'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='assumpte'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='text_identifier',
            field=models.CharField(max_length=100, unique=True, verbose_name='identificador'),
        ),
    ]
